apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-ssm
  annotations:
    eks.amazon.aws/role-arn: arn:aws:iam::193400300103:role/eks-ssm-ps-prod-role
---

apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  serviceAccountName: oidc-ssm
  containers:
    - name: demo
      image: 193400300103.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-store:latest
      imagePullPolicy: Always
      env:
        - name: PARAMS
          value: "prod.payment.cart_port prod.payment.user_port prod.payment.cart_host"