apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  imagePullPolicy: Always
  containers:
    - name: demo
      image: 193400300103.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-store:latest
